<?xml version="1.0"?>
<package format="3">

  <name>environment_weather_simulator</name>

  <version>1.0.0</version>

  <description>
    Environment and Weather Simulator for autonomous systems.
    Supports configurable weather effects, environmental modeling,
    Gazebo world generation, digital twin integration,
    and sensor weather simulation.
  </description>

  <maintainer email="chetanya@example.com">
    Chetanya Barodiya
  </maintainer>

  <license>Apache-2.0</license>


  <!-- Build system -->
  <buildtool_depend>ament_python</buildtool_depend>


  <!-- Python -->
  <exec_depend>python3</exec_depend>
  <exec_depend>python3-yaml</exec_depend>


  <!-- ROS 2 Core -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ament_index_python</exec_depend>


  <!-- Launch -->
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>


  <!-- Gazebo Harmonic / ROS Jazzy -->
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>


  <!-- ROS Messages -->
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>


  <!-- TF -->
  <exec_depend>tf2_ros</exec_depend>


  <!-- Python package support -->
  <exec_depend>setuptools</exec_depend>


  <!-- Testing -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>


  <export>
    <build_type>ament_python</build_type>
  </export>


</package>