weather:
  effect: fog

generator:
  file: fog_generator.txt

world:
  source: ansa_world.sdf
  output: generated_world.sdf

simulation:
  precipitation: false
  fog: true
  snow: false
  dust: false
  storm: false

launch:
  auto_start: true