weather:
  effect: clear

generator:
  file: clear_generator.txt

world:
  source: ansa_world.sdf
  output: generated_world.sdf

simulation:
  precipitation: false
  fog: false
  snow: false
  dust: false
  storm: false
  thunder: false
  wind: normal

launch:
  auto_start: true